routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@welcome')->name('welcome');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function() {

    Route::get('doctors/data', 'DoctorsController@dataIndex')->name('doctors.data');
    Route::resource('doctors', 'DoctorsController');
    Route::get('patients/data', 'PatientsController@dataIndex')->name('patients.data');
    Route::resource('patients', 'PatientsController');
    Route::get('schedules/data', 'SchedulesController@dataIndex')->name('schedules.data');
    Route::resource('schedules', 'SchedulesController');
    Route::get('users/data', 'UsersController@dataIndex')->name('users.data');
    Route::resource('users', 'UsersController');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Hash;
use Illuminate\Http\Request;
use App\Repositories\Repository;
use App\User;
use App\Rules\ZeroOrMin;
use DataTables;

class UsersController extends Controller
{

    protected $user;

    public function __construct()
    {
        $this->user = new Repository(new User);
    }
    
    public function index()
    {
        $returns = [
            'js' => [ 'users' ]
        ];
        return view('users.index', $returns);
    }

    public function show($id)
    {
        $returns = [
            'user' => $this->user->preview($id),
            'disabled' => true
        ];
        return view('users.show', $returns);
    }

    public function create()
    {
        $returns = [
            'disabled' => false
        ];
        return view('users.create', $returns);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|unique:users,email',
            'password' => 'required|confirmed|min:6',
            'password_confirmation' => 'required|min:6'
        ]);

        $data = $request->all();
        $data['password'] = Hash::make($data['password']);
        $user = $this->user->create($data);
        if ($user) {
            $request->session()->flash('success', __('messages.created_successfully'));
            return redirect(route('users.show', $user->id));
        }
        return redirect()->back()->withInput();
    }

    public function edit($id)
    {
        $returns = [
            'user' => $this->user->preview($id),
            'disabled' => false
        ];
        return view('users.edit', $returns);
    }

    public function update($id, Request $request)
    {
        $this->validate($request, [
            'email' => 'unique:users,email,'.$id,
            'password' => ['confirmed', new ZeroOrMin(6)]
        ]);

        $data = $request->all();
        if ($data['password']) {
            $data['password'] = Hash::make($data['password']);
        } else {
            unset($data['password']);
        }
        $result = $this->user->update($data, $id);
        if ($result) {
            return redirect(route('users.show', $id));
        }
        return redirect()->back()->withInput();
    }

    public function destroy($id)
    {
        $this->user->delete($id);
        return redirect(route('users.index'));
    }

    public function dataIndex()
    {
        $users = $this->user->getModel();

        $users = $users->select('id', 'name', 'email');

        $users = $users->get();

        return DataTables::of($users)->make();
    }

}

resources/views/users/_form.blade.php
@include('components.alerts')

<div class="form-group">
    <label for="name">{{ __('validation.attributes.name') }}</label>
    <input type="text" class="form-control" id="name" 
        name="name" aria-describedby="nameHelp" required
        value="{{ $user->name ?? old('name') }}" {{ $disabled ? 'disabled' : null }}>
    <small id="nameHelp" class="form-text text-muted">{{ __('views.required') }}</small>
</div>

<div class="form-group">
    <label for="email">{{ __('validation.attributes.email') }}</label>
    <input type="email" class="form-control" id="email" 
        name="email" aria-describedby="emailHelp" required
        value="{{ $user->email ?? old('email') }}" {{ $disabled ? 'disabled' : null }}>
    <small id="emailHelp" class="form-text text-muted">{{ __('views.required') }}</small>
</div>

@unless ($disabled)
    <div class="form-group">
        <label for="password">{{ __('validation.attributes.password') }}</label>
        <input type="password" class="form-control" id="password" 
            name="password" aria-describedby="passwordHelp" {{ $user->password ?? 'required' }}>
        <small id="passwordHelp" class="form-text text-muted">{{ __('passwords.password') }}</small>
    </div>

    <div class="form-group">
        <label for="password_confirmation">{{ __('validation.attributes.password_confirmation') }}</label>
        <input type="password" class="form-control" id="password_confirmation" 
            name="password_confirmation" aria-describedby="passwordConfirmationHelp" {{ $user->password ?? 'required' }}>
        <small id="passwordConfirmationHelp" class="form-text text-muted">{{ __('passwords.confirmation') }}</small>
    </div>
@endunless

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ trans_choice('views.users', 1) }}</div>

                <div class="card-body">
                    
                    <form class="form" action="{{ route('users.store') }}" method="post">
                        @csrf
                        
                        @include('users._form')

                        <div class="btn-group" role="group">
                            <button class="btn btn-success" type="submit">{{ __('views.save') }}</button>
                            <button class="btn btn-secondary" type="reset">{{ __('views.reset') }}</button>
                        </div>

                        <a class="float-right" href="{{ route('users.index') }}">
                            {{ __('views.back_to') }}
                            {{ trans_choice('views.users', 2) }}
                        </a>

                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ trans_choice('views.users', 1) }}</div>

                <div class="card-body">
                    
                    <form class="form" action="{{ route('users.update', $user->id) }}" method="post">
                        @csrf
                        <input type="hidden" name="_method" value="patch">
                        
                        @include('users._form')

                        <div class="btn-group" role="group">
                            <button class="btn btn-success" type="submit">{{ __('views.save') }}</button>
                            <button class="btn btn-secondary" type="reset">{{ __('views.reset') }}</button>
                        </div>

                        <a class="float-right" href="{{ route('users.index') }}">
                            {{ __('views.back_to') }}
                            {{ trans_choice('views.users', 2) }}
                        </a>

                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ trans_choice('views.users', 2) }}</div>

                <div class="card-body">

                    <p>
                        <a class="btn btn-outline-primary" href="{{ route('users.create') }}">
                            {{ __('views.add') }}
                        </a>
                    </p>
                    
                    <div class="table-responsive">
                        <table id="users-table" class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>{{ __('validation.attributes.id') }}</th>
                                    <th>{{ __('validation.attributes.name') }}</th>
                                    <th>{{ __('validation.attributes.email') }}</th>
                                    <th>{{ trans_choice('views.actions', 2) }}</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ trans_choice('views.users', 1) }}</div>

                <div class="card-body">
                    
                    <div class="form">

                        @include('users._form')

                        <a class="float-right" href="{{ route('users.index') }}">
                            {{ __('views.back_to') }}
                            {{ trans_choice('views.users', 2) }}
                        </a>

                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@endsection