routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@welcome')->name('welcome');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function() {

    Route::get('doctors/data', 'DoctorsController@dataIndex')->name('doctors.data');
    Route::resource('doctors', 'DoctorsController');
    Route::get('patients/data', 'PatientsController@dataIndex')->name('patients.data');
    Route::resource('patients', 'PatientsController');
    Route::get('schedules/data', 'SchedulesController@dataIndex')->name('schedules.data');
    Route::resource('schedules', 'SchedulesController');
    Route::get('users/data', 'UsersController@dataIndex')->name('users.data');
    Route::resource('users', 'UsersController');

});

app/Doctor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Doctor extends Model
{
    
    protected $table = 'doctors';

    protected $fillable = [ 
        'name', 'crm', 'status',
        'register_by_user_id'
    ];

    public function registerByUser()
    {
        return $this->belongsTo('App\User', 'register_by_user_id', 'id');
    }

}

app/Http/Controllers/Api/DoctorsController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Doctor;
use App\Repositories\Repository;
use App\Http\Resources\DoctorsResource;

class DoctorsController extends Controller
{
    protected $doctor;

    public function __construct()
    {
        $this->doctor = new Repository(new Doctor);
    }

    public function index()
    {
        return DoctorsResource::collection($this->doctor->all());
    }

}

app/Http/Controllers/DoctorsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Repositories\Repository;
use App\Doctor;
use DataTables;

class DoctorsController extends Controller
{
    
    protected $doctor;

    public function __construct()
    {
        $this->doctor = new Repository(new Doctor);
    }
    
    public function index()
    {
        $returns = [
            'js' => [ 'doctors' ]
        ];
        return view('doctors.index', $returns);
    }

    public function show($id)
    {
        $returns = [
            'doctor' => $this->doctor->preview($id),
            'disabled' => true
        ];
        return view('doctors.show', $returns);
    }

    public function create()
    {
        $returns = [
            'disabled' => false
        ];
        return view('doctors.create', $returns);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:100',
            'crm' => 'required|unique:doctors,crm|max:10'
        ]);

        $data = $request->all();
        $data['register_by_user_id'] = Auth::user()->id;
        $doctor = $this->doctor->create($data);
        if ($doctor) {
            return redirect(route('doctors.show', $doctor->id));
        }
        return redirect()->back()->withInput();
    }

    public function edit($id)
    {
        $returns = [
            'doctor' => $this->doctor->preview($id),
            'disabled' => false
        ];
        return view('doctors.edit', $returns);
    }

    public function update($id, Request $request)
    {
        $this->validate($request, [
            'crm' => 'max:10|unique:doctors,crm,'.$id
        ]);

        $data = $request->all();
        $result = $this->doctor->update($data, $id);
        if ($result) {
            return redirect(route('doctors.show', $id));
        }
        return redirect()->back()->withInput();
    }

    public function destroy($id)
    {
        $this->doctor->delete($id);
        return redirect(route('doctors.index'));
    }

    public function dataIndex()
    {
        $doctors = $this->doctor->getModel();

        $doctors = $doctors->select('id', 'name', 'crm');

        $doctors = $doctors->get();

        return DataTables::of($doctors)->make();
    }
    
}

resources/views/doctors/_form.blade.php
@include('components.alerts')

<div class="form-group">
    <label for="name">{{ __('validation.attributes.name') }}</label>
    <input type="text" class="form-control" id="name" 
        name="name" aria-describedby="nameHelp" required
        value="{{ $doctor->name ?? old('name') }}" {{ $disabled ? 'disabled' : null }}>
    <small id="nameHelp" class="form-text text-muted">{{ __('views.required') }}</small>
</div>

<div class="form-group">
    <label for="crm">{{ __('validation.attributes.crm') }}</label>
    <input type="text" class="form-control" id="crm" 
        name="crm" aria-describedby="crmHelp" required
        value="{{ $doctor->crm ?? old('crm') }}" {{ $disabled ? 'disabled' : null }}>
    <small id="crmHelp" class="form-text text-muted">{{ __('views.required') }}</small>
</div>

<div class="form-group">
    <label for="status">{{ __('validation.attributes.status') }}</label>
    <div class="custom-control custom-radio">
        <input type="radio" id="statusActive" name="status" 
            class="custom-control-input" {{ $disabled ? 'disabled' : null }}
            {{ isset($doctor) && $doctor->status ? 'checked' : null  }} value="1">
        <label class="custom-control-label" for="statusActive">{{ __('views.active') }}</label>
    </div>
    <div class="custom-control custom-radio">
        <input type="radio" id="statusInactive" name="status" 
            class="custom-control-input" {{ $disabled ? 'disabled' : null }}
            {{ isset($doctor) && $doctor->status == 0 ? 'checked' : null  }} value="0">
        <label class="custom-control-label" for="statusInactive">{{ __('views.inactive') }}</label>
    </div>
</div>

resources/views/doctors/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ trans_choice('views.doctors', 1) }}</div>

                <div class="card-body">
                    
                    <form class="form" action="{{ route('doctors.store') }}" method="post">
                        @csrf
                        
                        @include('doctors._form')

                        <div class="btn-group" role="group">
                            <button class="btn btn-success" type="submit">{{ __('views.save') }}</button>
                            <button class="btn btn-secondary" type="reset">{{ __('views.reset') }}</button>
                        </div>

                        <a class="float-right" href="{{ route('doctors.index') }}">
                            {{ __('views.back_to') }}
                            {{ trans_choice('views.doctors', 2) }}
                        </a>

                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/doctors/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ trans_choice('views.doctors', 1) }}</div>

                <div class="card-body">
                    
                    <form class="form" action="{{ route('doctors.update', $doctor->id) }}" method="post">
                        @csrf
                        <input type="hidden" name="_method" value="patch">
                        
                        @include('doctors._form')

                        <div class="btn-group" role="group">
                            <button class="btn btn-success" type="submit">{{ __('views.save') }}</button>
                            <button class="btn btn-secondary" type="reset">{{ __('views.reset') }}</button>
                        </div>

                        <a class="float-right" href="{{ route('doctors.index') }}">
                            {{ __('views.back_to') }}
                            {{ trans_choice('views.doctors', 2) }}
                        </a>

                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/doctors/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ trans_choice('views.doctors', 2) }}</div>

                <div class="card-body">

                    <p>
                        <a class="btn btn-outline-primary" href="{{ route('doctors.create') }}">
                            {{ __('views.add') }}
                        </a>
                    </p>
                    
                    <div class="table-responsive">
                        <table id="doctors-table" class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>{{ __('validation.attributes.id') }}</th>
                                    <th>{{ __('validation.attributes.name') }}</th>
                                    <th>{{ __('validation.attributes.crm') }}</th>
                                    <th>{{ trans_choice('views.actions', 2) }}</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/doctors/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ trans_choice('views.doctors', 1) }}</div>

                <div class="card-body">
                    
                    <div class="form">

                        @include('doctors._form')

                        <a class="float-right" href="{{ route('doctors.index') }}">
                            {{ __('views.back_to') }}
                            {{ trans_choice('views.doctors', 2) }}
                        </a>

                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@endsection