routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@welcome')->name('welcome');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function() {

    Route::get('doctors/data', 'DoctorsController@dataIndex')->name('doctors.data');
    Route::resource('doctors', 'DoctorsController');
    Route::get('patients/data', 'PatientsController@dataIndex')->name('patients.data');
    Route::resource('patients', 'PatientsController');
    Route::get('schedules/data', 'SchedulesController@dataIndex')->name('schedules.data');
    Route::resource('schedules', 'SchedulesController');
    Route::get('users/data', 'UsersController@dataIndex')->name('users.data');
    Route::resource('users', 'UsersController');

});

app/Patient.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    
    protected $table = 'patients';

    protected $fillable = [ 
        'name', 'cpf', 'status',
        'register_by_user_id'
    ];

    public function registerByUser()
    {
        return $this->belongsTo('App\User', 'register_by_user_id', 'id');
    }

}

app/Http/Controllers/PatientsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Repositories\Repository;
use App\Patient;
use DataTables;

class PatientsController extends Controller
{
    
    protected $patient;

    public function __construct()
    {
        $this->patient = new Repository(new Patient);
    }
    
    public function index()
    {
        $returns = [
            'js' => [ 'patients' ]
        ];
        return view('patients.index', $returns);
    }

    public function show($id)
    {
        $returns = [
            'patient' => $this->patient->preview($id),
            'disabled' => true
        ];
        return view('patients.show', $returns);
    }

    public function create()
    {
        $returns = [
            'disabled' => false
        ];
        return view('patients.create', $returns);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:100',
            'cpf' => 'required|unique:patients,cpf|max:11'
        ]);

        $data = $request->all();
        $data['register_by_user_id'] = Auth::user()->id;
        $patient = $this->patient->create($data);
        if ($patient) {
            return redirect(route('patients.show', $patient->id));
        }
        return redirect()->back()->withInput();
    }

    public function edit($id)
    {
        $returns = [
            'patient' => $this->patient->preview($id),
            'disabled' => false
        ];
        return view('patients.edit', $returns);
    }

    public function update($id, Request $request)
    {
        $this->validate($request, [
            'cpf' => 'max:11|unique:patients,cpf,'.$id
        ]);

        $data = $request->all();
        $result = $this->patient->update($data, $id);
        if ($result) {
            return redirect(route('patients.show', $id));
        }
        return redirect()->back()->withInput();
    }

    public function destroy($id)
    {
        $this->patient->delete($id);
        return redirect(route('patients.index'));
    }

    public function dataIndex()
    {
        $patients = $this->patient->getModel();

        $patients = $patients->select('id', 'name', 'cpf');

        $patients = $patients->get();

        return DataTables::of($patients)->make();
    }

}

resources/views/patients/_form.blade.php
@include('components.alerts')

<div class="form-group">
    <label for="name">{{ __('validation.attributes.name') }}</label>
    <input type="text" class="form-control" id="name" 
        name="name" aria-describedby="nameHelp" required
        value="{{ $patient->name ?? old('name') }}" {{ $disabled ? 'disabled' : null }}>
    <small id="nameHelp" class="form-text text-muted">{{ __('views.required') }}</small>
</div>

<div class="form-group">
    <label for="cpf">{{ __('validation.attributes.cpf') }}</label>
    <input type="text" class="form-control" id="cpf" 
        name="cpf" aria-describedby="cpfHelp" required
        value="{{ $patient->cpf ?? old('cpf') }}" {{ $disabled ? 'disabled' : null }}>
    <small id="cpfHelp" class="form-text text-muted">{{ __('views.required') }} - 
        {{ __('messages.only_number') }}</small>
</div>

<div class="form-group">
    <label for="status">{{ __('validation.attributes.status') }}</label>
    <div class="custom-control custom-radio">
        <input type="radio" id="statusActive" name="status" 
            class="custom-control-input" {{ $disabled ? 'disabled' : null }}
            {{ isset($patient) && $patient->status ? 'checked' : null  }} value="1">
        <label class="custom-control-label" for="statusActive">{{ __('views.active') }}</label>
    </div>
    <div class="custom-control custom-radio">
        <input type="radio" id="statusInactive" name="status" 
            class="custom-control-input" {{ $disabled ? 'disabled' : null }}
            {{ isset($patient) && $patient->status == 0 ? 'checked' : null  }} value="0">
        <label class="custom-control-label" for="statusInactive">{{ __('views.inactive') }}</label>
    </div>
</div>

resources/views/patients/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ trans_choice('views.patients', 1) }}</div>

                <div class="card-body">
                    
                    <form class="form" action="{{ route('patients.store') }}" method="post">
                        @csrf
                        
                        @include('patients._form')

                        <div class="btn-group" role="group">
                            <button class="btn btn-success" type="submit">{{ __('views.save') }}</button>
                            <button class="btn btn-secondary" type="reset">{{ __('views.reset') }}</button>
                        </div>

                        <a class="float-right" href="{{ route('patients.index') }}">
                            {{ __('views.back_to') }}
                            {{ trans_choice('views.patients', 2) }}
                        </a>

                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/patients/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ trans_choice('views.patients', 1) }}</div>

                <div class="card-body">
                    
                    <form class="form" action="{{ route('patients.update', $patient->id) }}" method="post">
                        @csrf
                        <input type="hidden" name="_method" value="patch">
                        
                        @include('patients._form')

                        <div class="btn-group" role="group">
                            <button class="btn btn-success" type="submit">{{ __('views.save') }}</button>
                            <button class="btn btn-secondary" type="reset">{{ __('views.reset') }}</button>
                        </div>

                        <a class="float-right" href="{{ route('patients.index') }}">
                            {{ __('views.back_to') }}
                            {{ trans_choice('views.patients', 2) }}
                        </a>

                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/patients/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ trans_choice('views.patients', 2) }}</div>

                <div class="card-body">

                    <p>
                        <a class="btn btn-outline-primary" href="{{ route('patients.create') }}">
                            {{ __('views.add') }}
                        </a>
                    </p>
                    
                    <div class="table-responsive">
                        <table id="patients-table" class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>{{ __('validation.attributes.id') }}</th>
                                    <th>{{ __('validation.attributes.name') }}</th>
                                    <th>{{ __('validation.attributes.cpf') }}</th>
                                    <th>{{ trans_choice('views.actions', 2) }}</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/patients/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ trans_choice('views.patients', 1) }}</div>

                <div class="card-body">
                    
                    <div class="form">

                        @include('patients._form')

                        <a class="float-right" href="{{ route('patients.index') }}">
                            {{ __('views.back_to') }}
                            {{ trans_choice('views.patients', 2) }}
                        </a>

                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@endsection