routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@welcome')->name('welcome');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function() {

    Route::get('doctors/data', 'DoctorsController@dataIndex')->name('doctors.data');
    Route::resource('doctors', 'DoctorsController');
    Route::get('patients/data', 'PatientsController@dataIndex')->name('patients.data');
    Route::resource('patients', 'PatientsController');
    Route::get('schedules/data', 'SchedulesController@dataIndex')->name('schedules.data');
    Route::resource('schedules', 'SchedulesController');
    Route::get('users/data', 'UsersController@dataIndex')->name('users.data');
    Route::resource('users', 'UsersController');

});

app/Schedule.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Schedule extends Model
{
    
    protected $table = 'schedules';

    protected $fillable = [ 
        'date_time', 'description', 'exams',
        'patient_id', 'doctor_id', 'register_by_user_id',
        'status'
    ];

    public function patient()
    {
        return $this->belongsTo('App\Patient');
    }

    public function doctor()
    {
        return $this->belongsTo('App\Doctor');
    }

    public function registerByUser()
    {
        return $this->belongsTo('App\User', 'register_by_user_id', 'id');
    }

    public static function getStatus()
    {
        return [
            'CONSULTED', 'CANCELED', 'MISSED', 
            'SCHEDULED'
        ];
    }

}

app/Http/Controllers/SchedulesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use App\Http\Requests\ScheduleRequest;
use App\Repositories\Repository;
use App\Doctor;
use App\Patient;
use App\Schedule;
use DataTables;

class SchedulesController extends Controller
{
    
    protected $schedule;
    protected $patient;
    protected $doctor;

    public function __construct()
    {
        $this->doctor = new Repository(new Doctor);
        $this->patient = new Repository(new Patient);
        $this->schedule = new Repository(new Schedule);
    }
    
    public function index()
    {
        $returns = [
            'js' => [ 'schedules' ]
        ];
        return view('schedules.index', $returns);
    }

    public function show($id)
    {
        $returns = [
            'schedule' => $this->schedule->preview($id),
            'disabled' => true,
            'patients' => $this->patient->getModel()->where('status', 1)->get(),
            'doctors' => $this->doctor->getModel()->where('status', 1)->get(),
            'status' => Schedule::getStatus(),
        ];
        return view('schedules.show', $returns);
    }

    public function create()
    {
        $returns = [
            'disabled' => false,
            'patients' => $this->patient->getModel()->where('status', 1)->get(),
            'doctors' => $this->doctor->getModel()->where('status', 1)->get(),
            'status' => Schedule::getStatus(),
            'js' => [ 'schedules' ],
        ];
        return view('schedules.create', $returns);
    }

    public function store(ScheduleRequest $request)
    {
        $data = $request->all();
        $data['register_by_user_id'] = Auth::user()->id;
        $examsJson = [];
        if ($request->exams) {
            foreach ($request->exams as $exam) {
                $filename = $exam->store('public/exams');
                $examsJson[] = $filename;
            }
        }
        $data['exams'] = json_encode($examsJson);
        $schedule = $this->schedule->create($data);
        if ($schedule) {
            return redirect(route('schedules.show', $schedule->id));
        }
        return redirect()->back()->withInput();
    }

    public function edit($id)
    {
        $returns = [
            'schedule' => $this->schedule->preview($id),
            'disabled' => false,
            'patients' => $this->patient->getModel()->where('status', 1)->get(),
            'doctors' => $this->doctor->getModel()->where('status', 1)->get(),
            'status' => Schedule::getStatus(),
        ];
        return view('schedules.edit', $returns);
    }

    public function update($id, ScheduleRequest $request)
    {
        $schedule = $this->schedule->preview($id);
        $data = $request->all();
        $examsJson = json_decode($schedule->exams);
        if ($request->exams) {
            foreach ($request->exams as $exam) {
                $filename = $exam->store('public/exams');
                $examsJson[] = $filename;
            }
        }
        $data['exams'] = json_encode($examsJson);
        $result = $this->schedule->update($data, $id);
        if ($result) {
            return redirect(route('schedules.show', $id));
        }
        return redirect()->back()->withInput();
    }

    public function destroy($id)
    {
        $this->schedule->delete($id);
        return redirect(route('schedules.index'));
    }

    public function dataIndex()
    {
        $schedules = $this->schedule->getModel();

        $schedules = $schedules->select('schedules.id', 'schedules.date_time', 'patients.name as patient', 
            'doctors.name as doctor', 'schedules.status');
        
        $schedules = $schedules->join('patients', 'patients.id', '=', 'schedules.patient_id');
        $schedules = $schedules->join('doctors', 'doctors.id', '=', 'schedules.doctor_id');

        $schedules = $schedules->get();

        return DataTables::of($schedules)->make();
    }

}

resources/views/schedules/_form.blade.php
@include('components.alerts')

<div class="form-group">
    <div class="form-group">
        <label for="patient_id">{{ __('validation.attributes.patient_id') }}</label>
        <select class="select2 form-control" id="patient_id" name="patient_id"
            {{ $disabled ? 'disabled' : null }}>
            <option value="0" selected disabled>{{ __('messages.select_a_patient') }}</option>
            @foreach ($patients as $patient)
                <option value="{{ $patient->id }}" 
                    {{ isset($schedule) && $schedule->patient_id == $patient->id ? 'selected' : null }}>
                    {{ $patient->name }}
                </option>
            @endforeach
        </select>
    </div>
</div>

<div class="form-group">
    <div class="form-group">
        <label for="doctor_id">{{ __('validation.attributes.doctor_id') }}</label>
        <select class="select2 form-control" id="doctor_id" name="doctor_id"
            {{ $disabled ? 'disabled' : null }}>
            <option value="0" selected disabled>{{ __('messages.select_a_doctor') }}</option>
            @foreach ($doctors as $doctor)
                <option value="{{ $doctor->id }}"
                    {{ isset($schedule) && $doctor->id == $schedule->doctor_id ? 'selected' : null }}>
                    {{ $doctor->name }}
                </option>
            @endforeach
        </select>
    </div>
</div>

<div class="form-group">
    <label for="date_time">{{ __('validation.attributes.date_time') }}</label>
    <input type="datetime-local" class="form-control" id="date_time" 
        name="date_time" aria-describedby="dateTimeHelp" required
        value="{{ isset($schedule) ? date('Y-m-d\TH:i:s', strtotime($schedule->date_time)) : old('date_time') }}" {{ $disabled ? 'disabled' : null }}>
    <small id="dateTimeHelp" class="form-text text-muted">{{ __('views.required') }}</small>
</div>

<div class="form-group">
    <label for="description">{{ __('validation.attributes.description') }}</label>
    <textarea class="form-control" id="description" rows="3"
        required name="description" {{ $disabled ? 'disabled' : null }}
        >{{ $schedule->description ?? old('description') }}</textarea>
    <small id="descriptionHelp" class="form-text text-muted">{{ __('views.required') }}</small>
</div>

<div class="form-group">
    <label for="exams">{{ __('validation.attributes.exams') }}</label>
    @unless ($disabled)
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="exams" 
                name="exams[]" multiple>
            <label class="custom-file-label" for="exams">{{ __('views.choose_file') }}</label>
        </div>
    @endunless
    @php
        $exams = $schedule->exams ?? null;
        if ($exams) {
            $exams = json_decode($exams);
        } else {
            $exams = [];
        }
    @endphp
    <ul>
        @foreach ($exams as $key => $exam)
            <li>
                <a href="{{ asset("storage/$exam") }}" target="_blank">
                    {{ trans_choice('views.exams', 1) . ' ' . ++$key }} 
                </a>
            </li>
        @endforeach
    </ul>
</div>

<div class="form-group">
    <div class="form-group">
        <label for="status">{{ __('validation.attributes.status') }}</label>
        <select class="form-control" id="status" name="status"
            {{ $disabled ? 'disabled' : null }}>
            <option value="0" selected disabled>{{ __('messages.select_an_option') }}</option>
            @foreach ($status as $item)
                <option value="{{ $item }}"
                    {{ isset($schedule) && $schedule->status == $item ? 'selected' : null }}>
                    {{ __("views.schedule_status.$item") }}
                </option>
            @endforeach
        </select>
    </div>
</div>

resources/views/schedules/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ trans_choice('views.schedules', 1) }}</div>

                <div class="card-body">
                    
                    <form class="form" action="{{ route('schedules.store') }}" method="post"
                        enctype="multipart/form-data">
                        @csrf
                        
                        @include('schedules._form')

                        <div class="btn-group" role="group">
                            <button class="btn btn-success" type="submit">{{ __('views.save') }}</button>
                            <button class="btn btn-secondary" type="reset">{{ __('views.reset') }}</button>
                        </div>

                        <a class="float-right" href="{{ route('schedules.index') }}">
                            {{ __('views.back_to') }}
                            {{ trans_choice('views.schedules', 2) }}
                        </a>

                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/schedules/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ trans_choice('views.schedules', 1) }}</div>

                <div class="card-body">
                    
                    <form class="form" action="{{ route('schedules.update', $schedule->id) }}" method="post"
                        enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" name="_method" value="patch">
                        
                        @include('schedules._form')

                        <div class="btn-group" role="group">
                            <button class="btn btn-success" type="submit">{{ __('views.save') }}</button>
                            <button class="btn btn-secondary" type="reset">{{ __('views.reset') }}</button>
                        </div>

                        <a class="float-right" href="{{ route('schedules.index') }}">
                            {{ __('views.back_to') }}
                            {{ trans_choice('views.schedules', 2) }}
                        </a>

                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/schedules/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ trans_choice('views.schedules', 2) }}</div>

                <div class="card-body">

                    <p>
                        <a class="btn btn-outline-primary" href="{{ route('schedules.create') }}">
                            {{ __('views.add') }}
                        </a>
                    </p>
                    
                    <div class="table-responsive">
                        <table id="schedules-table" class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>{{ __('validation.attributes.id') }}</th>
                                    <th>{{ __('validation.attributes.date_time') }}</th>
                                    <th>{{ __('validation.attributes.patient_id') }}</th>
                                    <th>{{ __('validation.attributes.doctor_id') }}</th>
                                    {{-- <th>{{ __('views.has_exams') }}</th> --}}
                                    <th>{{ __('validation.attributes.status') }}</th>
                                    <th>{{ trans_choice('views.actions', 2) }}</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/schedules/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ trans_choice('views.schedules', 1) }}</div>

                <div class="card-body">
                    
                    <div class="form">

                        @include('schedules._form')

                        <a class="float-right" href="{{ route('schedules.index') }}">
                            {{ __('views.back_to') }}
                            {{ trans_choice('views.schedules', 2) }}
                        </a>

                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

@endsection